config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'messages/inbox#index'

  namespace :messages do
    get '/inbox', to: 'inbox#index'
    get '/sent',  to: 'sent#index'
    get '/drafts', to: 'drafts#index'
  end
  resources :messages, except: :index
end

app/views/shared/_flash_messages.html.erb
<div class="col-12" id="flash_messages">
  <% flash.each do |type, message| %>
    <div class="alert <%= alert_class_for(type) %>" role='alert'>
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler navbar-toggler-right" data-target="#navbar" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%= link_to 'Post', root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse float-left" id="navbar">
    <% if signed_in? %>
      <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="http://example.com" id="navbar_dropdown_signed_in">
        Hi, <%= current_user.first_name %>
      </a>
      <div aria-labelledby="navbar_dropdown_signed_in" class="dropdown-menu">
        <%= link_to 'Settings', edit_user_registration_path, class: 'dropdown-item' %>
        <%= link_to 'Sign out', destroy_user_session_path, data: { method: :delete }, class: 'dropdown-item' %>
      </div>
    <% else %>
      <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="http://example.com" id="navbar_dropdown_signed_out">
        SIGNED OUT
      </a>
      <div aria-labelledby="navbar_dropdown_signed_out" class="dropdown-menu">
        <%= link_to 'Sign in', new_user_session_path, class: 'dropdown-item' %>
        <%= link_to 'Sign up', new_user_registration_path, class: 'dropdown-item' %>
      </div>
    <% end %>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<list-group>
  <%= link_to 'Inbox', messages_inbox_path, class: 'list-group-item' %>
  <%= link_to 'Sent', messages_sent_path, class: 'list-group-item' %>
  <%= link_to 'Drafts', messages_drafts_path, class: 'list-group-item' %>
</list-group>